[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Optional: Redirects or headers can be added here
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200 